name: CI

on:
  push:
    branches:
      - main
      - setup
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # Step 3: Cache pip dependencies
      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # Step 4: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 5: Check Python version
      - name: Check Python version
        run: python --version

      # Step 6: List installed dependencies (optional, for debugging)
      - name: List installed packages
        run: python -m pip list

      # Step 7: Run tests (won't fail if no tests exist)
      - name: Run tests
        run: |
          pip install pytest
          pytest || true
